
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/laundrycombo 

module laundrycombo(state, reset, clk, card_in, door_closed,
     done_washing1, done_washing2, done_drying, prewash_en,
     double_wash, dry_en, maintenance_mode, wash, ready, dry,
     door_unlocked, do_not_reset, can_accept_more_credit,
     pre_w_double_w_dry_selected);
  input reset, clk, card_in, door_closed, done_washing1, done_washing2,
       done_drying, prewash_en, double_wash, dry_en, maintenance_mode;
  output [8:0] state;
  output wash, ready, dry, door_unlocked, do_not_reset,
       can_accept_more_credit, pre_w_double_w_dry_selected;
  wire reset, clk, card_in, door_closed, done_washing1, done_washing2,
       done_drying, prewash_en, double_wash, dry_en, maintenance_mode;
  wire [8:0] state;
  wire wash, ready, dry, door_unlocked, do_not_reset,
       can_accept_more_credit, pre_w_double_w_dry_selected;
  wire n_1, n_2, n_3, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_96, n_117, n_119, n_123, n_124;
  assign can_accept_more_credit = state[3];
  assign do_not_reset = state[4];
  assign door_unlocked = state[7];
  assign dry = state[5];
  assign ready = state[8];
  assign wash = state[6];
  DFFHQX1 \state_reg[7] (.CK (clk), .D (n_96), .Q (state[7]));
  NOR4X1 g5956(.A (n_82), .B (n_65), .C (n_92), .D (n_123), .Y (n_96));
  DFFHQX1 \state_reg[6] (.CK (clk), .D (n_94), .Q (state[6]));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_93), .Q (state[0]));
  DFFHQX1 \state_reg[8] (.CK (clk), .D (n_91), .Q (state[8]));
  NOR4X1 g5959(.A (reset), .B (n_90), .C (n_87), .D (n_75), .Y (n_94));
  NAND2BX1 g5963(.AN (n_92), .B (n_88), .Y (n_93));
  OR4X1 g5961(.A (reset), .B (n_48), .C (n_86), .D (n_90), .Y (n_91));
  AOI21X1 g5966(.A0 (maintenance_mode), .A1 (n_80), .B0 (n_38), .Y
       (n_89));
  NOR4X1 g5967(.A (n_90), .B (n_62), .C (n_73), .D (n_79), .Y (n_88));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_83), .Q (state[1]));
  NAND4XL g5964(.A (n_85), .B (n_57), .C (n_77), .D (n_84), .Y (n_87));
  OAI221X1 g5968(.A0 (maintenance_mode), .A1 (n_69), .B0 (card_in), .B1
       (n_85), .C0 (n_84), .Y (n_86));
  NAND3BXL g5971(.AN (n_82), .B (n_81), .C (n_74), .Y (n_83));
  NAND2X1 g5972(.A (n_59), .B (n_78), .Y (n_80));
  OAI211X1 g5975(.A0 (n_5), .A1 (n_85), .B0 (n_117), .C0 (n_68), .Y
       (n_79));
  OAI21X1 g5976(.A0 (n_76), .A1 (n_44), .B0 (n_70), .Y (n_78));
  OAI21X1 g5981(.A0 (maintenance_mode), .A1 (n_76), .B0 (n_60), .Y
       (n_77));
  OR4X1 g5970(.A (n_24), .B (n_29), .C (n_75), .D (n_64), .Y (n_84));
  DFFHQX1 \state_reg[4] (.CK (clk), .D (n_66), .Q (state[4]));
  DFFHQX1 \state_reg[2] (.CK (clk), .D (n_72), .Q (state[2]));
  AOI221X1 g5977(.A0 (n_54), .A1 (n_53), .B0 (n_45), .B1 (n_49), .C0
       (n_73), .Y (n_74));
  DFFHQX1 \state_reg[3] (.CK (clk), .D (n_63), .Q (state[3]));
  OAI211X1 g5980(.A0 (n_36), .A1 (n_42), .B0 (n_50), .C0 (n_117), .Y
       (n_72));
  OAI211X1 g5982(.A0 (reset), .A1 (n_69), .B0 (n_56), .C0 (n_67), .Y
       (n_70));
  OA22X1 g5988(.A0 (maintenance_mode), .A1 (n_67), .B0 (reset), .B1
       (n_47), .Y (n_68));
  OR4X1 g5973(.A (n_82), .B (n_65), .C (n_92), .D (n_52), .Y (n_66));
  OAI211X1 g5979(.A0 (state[0]), .A1 (n_41), .B0 (n_35), .C0 (n_46), .Y
       (n_64));
  NAND2BXL g5984(.AN (n_62), .B (n_55), .Y (n_63));
  NAND2X1 g5989(.A (door_closed), .B (n_58), .Y (n_76));
  NAND2X1 g5990(.A (n_59), .B (n_58), .Y (n_60));
  OAI221X1 g5987(.A0 (reset), .A1 (n_57), .B0 (n_30), .B1 (n_56), .C0
       (n_55), .Y (n_73));
  NAND2BX1 g5999(.AN (n_54), .B (n_53), .Y (n_67));
  NOR2BX1 g6000(.AN (n_56), .B (n_53), .Y (n_58));
  OAI211X1 g5985(.A0 (n_8), .A1 (n_81), .B0 (n_40), .C0 (n_51), .Y
       (n_52));
  INVX1 g5991(.A (n_50), .Y (n_92));
  OAI21XL g5993(.A0 (door_closed), .A1 (n_59), .B0 (n_56), .Y (n_49));
  OAI22X1 g5994(.A0 (n_7), .A1 (n_81), .B0 (n_39), .B1 (n_27), .Y
       (n_62));
  DFFHQX1 \state_reg[5] (.CK (clk), .D (n_34), .Q (state[5]));
  AOI33XL g5995(.A0 (done_washing2), .A1 (n_3), .A2 (n_82), .B0 (n_65),
       .B1 (n_1), .B2 (state[0]), .Y (n_71));
  INVX1 g6001(.A (n_69), .Y (n_75));
  INVX1 g6003(.A (n_47), .Y (n_48));
  OAI2BB1X1 g6006(.A0N (n_37), .A1N (n_31), .B0 (n_17), .Y (n_46));
  NAND3BXL g5992(.AN (n_59), .B (door_closed), .C (n_45), .Y (n_50));
  AOI21X1 g6002(.A0 (state[0]), .A1 (n_124), .B0 (n_44), .Y (n_69));
  NAND3X1 g6004(.A (door_closed), .B (state[0]), .C (n_124), .Y (n_47));
  NAND3BXL g6005(.AN (reset), .B (n_42), .C (n_124), .Y (n_85));
  AOI221X1 g6007(.A0 (n_2), .A1 (n_18), .B0 (state[1]), .B1 (n_28), .C0
       (n_124), .Y (n_41));
  NAND2X1 g6009(.A (n_39), .B (n_38), .Y (n_40));
  NOR2X1 g6010(.A (n_32), .B (n_37), .Y (n_53));
  NAND2X1 g6011(.A (prewash_en), .B (n_65), .Y (n_36));
  OR2XL g6012(.A (n_33), .B (n_35), .Y (n_55));
  INVX1 g5996(.A (n_51), .Y (n_34));
  OAI33X1 g5998(.A0 (n_33), .A1 (n_25), .A2 (n_15), .B0 (n_32), .B1
       (n_23), .B2 (n_31), .Y (n_90));
  NAND3BXL g6013(.AN (reset), .B (n_30), .C (n_29), .Y (n_59));
  NAND3X1 g6014(.A (n_26), .B (n_42), .C (n_28), .Y (n_56));
  INVX1 g6016(.A (n_38), .Y (n_27));
  AOI33X1 g5997(.A0 (n_26), .A1 (n_25), .A2 (n_24), .B0 (n_20), .B1
       (n_23), .B2 (n_14), .Y (n_51));
  NOR2X1 g6015(.A (n_33), .B (n_22), .Y (n_82));
  NOR2X1 g6017(.A (n_32), .B (n_22), .Y (n_38));
  NOR2X1 g6018(.A (n_32), .B (n_21), .Y (n_65));
  NAND2BX1 g6019(.AN (n_30), .B (n_29), .Y (n_57));
  NAND2X1 g6020(.A (state[0]), .B (n_28), .Y (n_37));
  OR2XL g6021(.A (n_42), .B (n_21), .Y (n_35));
  NAND2X1 g6008(.A (n_20), .B (n_24), .Y (n_81));
  NOR2X1 g6025(.A (state[8]), .B (n_19), .Y (n_28));
  NAND2X1 g6026(.A (n_12), .B (n_18), .Y (n_22));
  NAND2X1 g6027(.A (state[2]), .B (n_18), .Y (n_21));
  NOR3X1 g6028(.A (state[1]), .B (state[0]), .C (n_16), .Y (n_44));
  NOR3X1 g6029(.A (n_17), .B (n_42), .C (n_16), .Y (n_29));
  INVXL g6022(.A (n_24), .Y (n_15));
  NOR4X1 g6023(.A (state[8]), .B (state[7]), .C (n_42), .D (n_9), .Y
       (n_24));
  INVX1 g6030(.A (n_31), .Y (n_14));
  NAND3BXL g6033(.AN (state[3]), .B (state[7]), .C (n_11), .Y (n_19));
  NOR2X1 g6032(.A (state[5]), .B (n_13), .Y (n_18));
  NAND3BXL g6031(.AN (n_13), .B (state[5]), .C (n_12), .Y (n_31));
  NAND2X1 g6034(.A (n_11), .B (n_10), .Y (n_16));
  NAND3X1 g6035(.A (state[4]), .B (state[6]), .C (n_10), .Y (n_13));
  NAND3X1 g6036(.A (state[6]), .B (state[3]), .C (n_6), .Y (n_9));
  INVXL g6041(.A (n_7), .Y (n_8));
  NOR2BX1 g6037(.AN (n_6), .B (state[6]), .Y (n_11));
  OAI2BB1X1 g6042(.A0N (double_wash), .A1N (door_closed), .B0 (n_30),
       .Y (n_7));
  OAI2BB1X1 g6043(.A0N (dry_en), .A1N (door_closed), .B0 (n_30), .Y
       (n_25));
  INVX1 g6053(.A (n_26), .Y (n_33));
  NOR3X1 g6038(.A (state[8]), .B (state[3]), .C (state[7]), .Y (n_10));
  NOR3X1 g6039(.A (state[4]), .B (state[5]), .C (state[2]), .Y (n_6));
  NOR2XL g6045(.A (door_closed), .B (n_5), .Y (n_54));
  OR3XL g6040(.A (dry_en), .B (double_wash), .C (prewash_en), .Y
       (pre_w_double_w_dry_selected));
  INVX1 g6048(.A (n_20), .Y (n_32));
  INVXL g6051(.A (n_39), .Y (n_3));
  NOR2X1 g6054(.A (reset), .B (n_17), .Y (n_26));
  NOR2X1 g6049(.A (reset), .B (state[1]), .Y (n_20));
  NAND2XL g6047(.A (door_closed), .B (card_in), .Y (n_30));
  NAND2XL g6052(.A (done_washing1), .B (door_closed), .Y (n_39));
  NAND2X1 g6046(.A (state[2]), .B (state[1]), .Y (n_2));
  NAND2XL g6044(.A (done_drying), .B (door_closed), .Y (n_23));
  NOR2X1 g6050(.A (state[2]), .B (state[0]), .Y (n_12));
  INVXL g6059(.A (door_closed), .Y (n_1));
  INVXL g6056(.A (card_in), .Y (n_5));
  INVX1 g6057(.A (state[0]), .Y (n_42));
  INVX1 g6060(.A (state[1]), .Y (n_17));
  INVXL g6058(.A (maintenance_mode), .Y (n_45));
  INVX1 drc_bufs(.A (n_119), .Y (n_117));
  INVX1 drc_bufs6071(.A (n_71), .Y (n_119));
  NAND4BX1 g2(.AN (n_73), .B (n_81), .C (n_51), .D (n_89), .Y (n_123));
  NOR3BX1 g6075(.AN (state[8]), .B (state[1]), .C (n_19), .Y (n_124));
endmodule

